"""Per-slide illustration filling for the teacher pack.

The teacher-pack prompt has the model emit `ELEMENT: image` fences carrying
only `scene` + `caption` + `width` — no bytes. This module finds those
fences, generates each picture with the image model on the Clodex
OpenAI-compatible endpoint (gpt-image-2) using the owner's fixed style
prefix, and injects the base64 bytes as `data`.

Contract with the platform importer (DIRECTIVE-slides-lean-plus-images):
- an image element with missing/invalid base64 HARD-FAILS the packet at
  import, so a failed generation must remove the WHOLE fence, never ship a
  data-less one;
- readable text/formulas never go into the image — the style prefix forbids
  them and the prompt keeps them out of `scene`.

Fail-open everywhere: no credential, endpoint down, or every image failing
must NEVER fail the job — the deck ships imageless with a warning and the
importer-side audit flags it.
"""

from __future__ import annotations

import asyncio
import json
import re

from loguru import logger

from app.config import settings

# The owner's fixed style prompt (verbatim from the directive). The scene is
# interpolated at the head; the style handles palette/composition and forbids
# readable text, logos and watermarks.
STYLE_PREFIX = (
    "Create an illustration of {scene} in my logistics illustration style: "
    "a friendly modern flat-vector illustration with a soft educational "
    "children's-book aesthetic. Use simplified rounded characters and objects, "
    "clean smooth shapes, minimal outlines, expressive but simple facial "
    "features, and gently exaggerated proportions. Use a light pastel palette "
    "of pale blue, turquoise, teal, mint green, warm yellow, cream, and subtle "
    "peach tones. Add soft diffused lighting, mild gradients, restrained "
    "shadows, and a crisp polished 2D finish. Use an eye-level landscape "
    "composition with the main subject clearly centered, important objects "
    "visible in the foreground, and a bright, tidy professional environment. "
    "Add lightly faded contextual symbols and subtle plants in the background. "
    "Keep the atmosphere optimistic, welcoming, focused, and professional. "
    "Polished commercial educational illustration quality. No photorealism, "
    "dark colors, heavy outlines, complex textures, dramatic contrast, "
    "readable text, logos, or watermarks."
)

# Both tolerated fence forms: kind on the fence line, or on the first line
# inside (canonical). Group 1/2 = kind, group 3 = JSON body.
_IMG_FENCE_RE = re.compile(
    r"```(?:ELEMENT:[ \t]*(image)[ \t]*\n|[ \t]*\nELEMENT:[ \t]*(image)[ \t]*\n)"
    r"(.*?)```",
    re.S,
)


def _client():
    """The Clodex OpenAI-compatible client (single-sourced auth handling)."""
    from app.services.api_transport import _clodex_client

    return _clodex_client()


async def _generate_one(client, scene: str) -> str:
    """One image call → base64 string. Tries the compressed-jpeg parameter set
    first (keeps the packet small), falls back to the minimal call if the
    mirror rejects the extra kwargs."""
    prompt = STYLE_PREFIX.format(scene=scene)
    kwargs = dict(model=settings.deck_image_model, prompt=prompt,
                  size=settings.deck_image_size)
    try:
        resp = await client.images.generate(
            **kwargs, output_format="jpeg", output_compression=60,
        )
    except TypeError:
        resp = await client.images.generate(**kwargs)
    except Exception as exc:  # noqa: BLE001 — mirror may 400 unknown params
        if "output_format" in str(exc) or "output_compression" in str(exc) or "400" in str(exc):
            resp = await client.images.generate(**kwargs)
        else:
            raise
    b64 = getattr(resp.data[0], "b64_json", None)
    if not b64:
        raise RuntimeError("image response carried no b64_json")
    return b64


async def fill_images(md: str, *, job_id=None) -> tuple[str, int, int]:
    """Inject generated bytes into every data-less image element.

    Returns (new_md, generated, failed). Fences whose generation fails (or
    that exceed the per-deck cap) are REMOVED entirely. Raises only
    AuthEnvError-shaped credential absence to the caller's discretion — no:
    even that is caught here; a missing key returns the md untouched with
    every image counted failed=0/generated=0 and a note via logger (the
    caller adds the warning).
    """
    matches = list(_IMG_FENCE_RE.finditer(md))
    todo = []
    for m in matches:
        try:
            obj = json.loads(m.group(3))
        except Exception:  # noqa: BLE001 — malformed json → strip at apply time
            todo.append((m, None))
            continue
        if obj.get("data"):
            continue  # already filled
        todo.append((m, obj))
    if not todo:
        return md, 0, 0

    try:
        client = _client()
    except Exception as exc:  # noqa: BLE001 — no credential on this machine
        logger.warning(f"deck_images: no image client ({exc!r}) — deck ships imageless")
        # strip ALL data-less fences: the importer hard-fails on data-less ones
        out = md
        for m, _ in reversed(todo):
            out = out[:m.start()] + out[m.end():]
        return out, 0, len(todo)

    sem = asyncio.Semaphore(3)
    results: dict[int, str | None] = {}

    async def _run(idx: int, obj) -> None:
        if obj is None or not obj.get("scene"):
            results[idx] = None
            return
        async with sem:
            try:
                results[idx] = await _generate_one(client, str(obj["scene"])[:500])
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    f"deck_images[job {job_id}]: scene {idx} failed ({exc!r})"
                )
                results[idx] = None

    capped = todo[: settings.deck_image_max]
    for m, _ in todo[settings.deck_image_max:]:
        logger.info(f"deck_images[job {job_id}]: over cap — stripping extra image")
    await asyncio.gather(*(_run(i, obj) for i, (_, obj) in enumerate(capped)))

    made = failed = 0
    out = md
    # apply right-to-left so match offsets stay valid
    for rev_idx in range(len(todo) - 1, -1, -1):
        m, obj = todo[rev_idx]
        b64 = results.get(rev_idx) if rev_idx < len(capped) else None
        if b64 and obj is not None:
            obj["data"] = b64
            block = "```\nELEMENT: image\n" + json.dumps(obj, ensure_ascii=False) + "\n```"
            out = out[:m.start()] + block + out[m.end():]
            made += 1
        else:
            out = out[:m.start()] + out[m.end():]
            failed += 1
    return out, made, failed
