"""Judge model selection (+ a capability-tier table kept for reference).

A validation judge must be at least as capable as the model that produced the
output. The simplest way to guarantee that is to judge with the STRONGEST model:
`settings.judge_model` (default claude-opus-4-7), which is >= every generator, so
no tier arithmetic is needed. The only special case is the no-self rule — a phase
generated by the judge model itself must be graded by a different peer.

`tier_of` / `_MODEL_TIER` are retained for reference + the manifest-completeness
test; judge selection no longer depends on them.
"""

from __future__ import annotations

from typing import Optional

from app.config import settings
from app.services.agent_models import default_model

# 1 = strongest. Every MODEL_MANIFEST model appears exactly once.
_MODEL_TIER: dict[str, int] = {
    # Tier 1 — Frontier
    "claude-opus-4-7": 1,
    "gpt-5.5": 1,
    "gemini-3.1-pro-preview": 1,
    # Tier 2 — Strong
    "claude-sonnet-4-6": 2,
    "gpt-5.2": 2,
    "gpt-5": 2,
    "gemini-3-flash-preview": 2,
    "gemini-2.5-pro": 2,
    # Tier 3 — Mid
    "claude-haiku-4-5-20251001": 3,
    "gpt-5-mini": 3,
    "gemini-3.1-flash-lite-preview": 3,
    "gemini-2.5-flash": 3,
    "kimi-code/kimi-for-coding": 3,
    # Tier 4 — Light
    "gpt-5-nano": 4,
    "gemini-2.5-flash-lite": 4,
    "opencode/deepseek-v4-flash-free": 4,
    "opencode/nemotron-3-super-free": 4,
    "opencode/mimo-v2.5-free": 4,
    "opencode/big-pickle": 4,
}

# Unknown model (shouldn't happen — manifest is enforced at /generate) -> assume
# Strong, so the judge errs toward a Frontier check rather than under-grading.
_DEFAULT_TIER = 2

# When the configured judge model IS the generator (e.g. an opus-generated phase
# judged by opus), fall back to a strong, INSTALLED, non-self peer so a model
# never grades its own output. gemini-3.1-pro-preview is the strongest non-claude
# model and is reliably on PATH here.
_SELF_FALLBACK: tuple[str, str] = ("gemini", "gemini-3.1-pro-preview")


def tier_of(provider: str, model: Optional[str]) -> int:
    """Capability tier (1=strongest) of (provider, model). `model=None` resolves
    to the provider's default model first. (Reference only — judge selection no
    longer uses this.)"""
    resolved = model or default_model(provider)
    return _MODEL_TIER.get(resolved or "", _DEFAULT_TIER)


def judge_model_for(gen_provider: str, gen_model: Optional[str]) -> tuple[str, str]:
    """Pick the judge (provider, model).

    The judge is ``settings.judge_provider`` / ``settings.judge_model`` (default
    claude / claude-opus-4-7 — the strongest model, so it is >= every generator).
    If that would be the generating model itself (no-self), fall back to a
    frontier non-self peer so a model never grades its own output.
    """
    judge = (settings.judge_provider, settings.judge_model)
    resolved_gen = (gen_provider, gen_model or default_model(gen_provider))
    return _SELF_FALLBACK if judge == resolved_gen else judge


def resolve_judge(
    gen_provider: str,
    gen_model: Optional[str],
    judge_provider: Optional[str],
    judge_model: Optional[str],
) -> tuple[str, str]:
    """Effective judge (provider, model). Explicit override wins, EXCEPT an exact
    self-grade (judge == generator) which is hard-swapped to a non-self peer. A
    NULL override falls back to the auto-tier judge."""
    if judge_provider is None:
        return judge_model_for(gen_provider, gen_model)
    resolved_gen = (gen_provider, gen_model or default_model(gen_provider))
    if (judge_provider, judge_model) == resolved_gen:
        return _SELF_FALLBACK
    return (judge_provider, judge_model)


def judge_advisory(
    gen_provider: str,
    gen_model: Optional[str],
    judge_provider: Optional[str],
    judge_model: Optional[str],
) -> Optional[str]:
    """Non-blocking advisory: warn when the RESOLVED judge is weaker (higher tier
    number) than the generator. None when judge >= generator."""
    j_prov, j_model = resolve_judge(gen_provider, gen_model, judge_provider, judge_model)
    if tier_of(j_prov, j_model) > tier_of(gen_provider, gen_model):
        return (f"judge ({j_prov}/{j_model}) is weaker than the generator "
                f"({gen_provider}/{gen_model}); grading may be unreliable")
    return None
