"""Unit tests for ``app.services.model_tiers``.

Coverage:
- Every manifest model gets a tier assignment.
- None model resolves to provider default, then its tier.
- Judge is one tier up and never claude.
- Top-tier generator gets non-self peer.
- Collision avoidance (primary == generator falls back to alternate).
- Light generator jumps multiple tiers (tier 4 → tier 3 judge).
"""

from __future__ import annotations

import pytest

from app.services.agent_models import MODEL_MANIFEST
from app.services import model_tiers as mt


def test_every_manifest_model_has_a_tier():
    """All models in MODEL_MANIFEST must have a tier assignment."""
    for provider, models in MODEL_MANIFEST.items():
        for model in models:
            t = mt.tier_of(provider, model)
            assert t in (1, 2, 3, 4), f"{provider}/{model} -> {t}"


def test_none_model_resolves_to_provider_default_tier():
    """model=None resolves to provider default, then its tier."""
    assert mt.tier_of("gemini", None) == mt.tier_of(
        "gemini", "gemini-3.1-pro-preview"
    )
    assert mt.tier_of("codex", None) == mt.tier_of("codex", "gpt-5.5")


def _pin_opus_judge(monkeypatch):
    monkeypatch.setattr(mt.settings, "judge_provider", "claude")
    monkeypatch.setattr(mt.settings, "judge_model", "claude-opus-4-7")


def test_judge_is_the_configured_strong_model(monkeypatch):
    """The judge is settings.judge_model (default claude-opus-4-7) for every
    generator, since the strongest model is >= all of them."""
    _pin_opus_judge(monkeypatch)
    assert mt.judge_model_for("claude", "claude-sonnet-4-6") == ("claude", "claude-opus-4-7")
    assert mt.judge_model_for("gemini", None) == ("claude", "claude-opus-4-7")  # post-failover
    assert mt.judge_model_for("codex", "gpt-5-nano") == ("claude", "claude-opus-4-7")


def test_judge_never_grades_itself(monkeypatch):
    """A phase generated by the judge model itself is graded by a non-self peer."""
    _pin_opus_judge(monkeypatch)
    j = mt.judge_model_for("claude", "claude-opus-4-7")
    assert j != ("claude", "claude-opus-4-7")
    assert j == ("gemini", "gemini-3.1-pro-preview")


def test_judge_model_is_configurable(monkeypatch):
    """Operators can move judging off claude via settings."""
    monkeypatch.setattr(mt.settings, "judge_provider", "gemini")
    monkeypatch.setattr(mt.settings, "judge_model", "gemini-3.1-pro-preview")
    assert mt.judge_model_for("claude", "claude-sonnet-4-6") == ("gemini", "gemini-3.1-pro-preview")
