"""Unit tests for ``app.services.model_tiers``.

Coverage:
- Every manifest model gets a tier assignment.
- None model resolves to provider default, then its tier.
- judge_model_for returns a strong non-self frontier peer (no settings read).
- Primary self-fallback: generator that is not the primary peer → primary peer.
- Alt self-fallback: generator IS the primary peer → alternate peer.
"""

from __future__ import annotations

import pytest

from app.services.agent_models import MODEL_MANIFEST
from app.services import model_tiers as mt


def test_every_manifest_model_has_a_tier():
    """All models in MODEL_MANIFEST must have a tier assignment."""
    for provider, models in MODEL_MANIFEST.items():
        for model in models:
            t = mt.tier_of(provider, model)
            assert t in (1, 2, 3, 4), f"{provider}/{model} -> {t}"


def test_none_model_resolves_to_provider_default_tier():
    """model=None resolves to provider default, then its tier."""
    assert mt.tier_of("gemini", None) == mt.tier_of(
        "gemini", "gemini-3.1-pro-preview"
    )
    assert mt.tier_of("codex", None) == mt.tier_of("codex", "gpt-5.5")


def test_judge_model_for_returns_primary_peer_for_ordinary_generator():
    """Any generator that is not the primary peer gets the primary peer as judge.
    The judge is a strong frontier peer, not a settings-derived value."""
    # gemini-2.5-flash (tier 3) — not the primary peer
    assert mt.judge_model_for("gemini", "gemini-2.5-flash") == ("claude", "claude-opus-4-7")
    # claude-sonnet (tier 2) — not the primary peer
    assert mt.judge_model_for("claude", "claude-sonnet-4-6") == ("claude", "claude-opus-4-7")
    # gemini with None model resolves to gemini-3.1-pro-preview — not primary peer
    assert mt.judge_model_for("gemini", None) == ("claude", "claude-opus-4-7")
    # codex generator — also not the primary peer
    assert mt.judge_model_for("codex", "gpt-5.4-mini") == ("claude", "claude-opus-4-7")


def test_judge_never_grades_itself_when_generator_is_primary_peer():
    """A phase generated by the PRIMARY peer (claude-opus-4-7) is graded by
    the ALTERNATE peer (gemini-3.1-pro-preview) — never itself."""
    j = mt.judge_model_for("claude", "claude-opus-4-7")
    assert j != ("claude", "claude-opus-4-7")
    assert j == ("gemini", "gemini-3.1-pro-preview")


def test_judge_model_for_is_deterministic_no_settings_dependency():
    """judge_model_for must return the same value regardless of any environment
    variable or settings value — the configured default lives in the DB row now."""
    # Call twice; result must be identical (no external state consulted).
    r1 = mt.judge_model_for("gemini", "gemini-2.5-flash")
    r2 = mt.judge_model_for("gemini", "gemini-2.5-flash")
    assert r1 == r2 == ("claude", "claude-opus-4-7")
