"""initial

Revision ID: 22c7641cf558
Revises: 
Create Date: 2026-04-30 09:30:20.545740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c7641cf558'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('gemini_file_uri', sa.String(length=512), nullable=True),
    sa.Column('gemini_file_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_books_content_sha256', 'books', ['content_sha256'], unique=False)
    op.create_table('toc_entries',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_number', sa.String(length=32), nullable=True),
    sa.Column('chapter_title', sa.Text(), nullable=True),
    sa.Column('section_number', sa.String(length=32), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_toc_entries_book_id_order', 'toc_entries', ['book_id', 'order_index'], unique=False)
    op.create_table('homework_jobs',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('toc_entry_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_phase', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('assembled_md', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['toc_entry_id'], ['toc_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_homework_jobs_book_toc', 'homework_jobs', ['book_id', 'toc_entry_id'], unique=False)
    op.create_index('ix_homework_jobs_status', 'homework_jobs', ['status'], unique=False)
    op.create_table('phase_outputs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('phase_name', sa.String(length=64), nullable=False),
    sa.Column('phase_order', sa.Integer(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('output_md', sa.Text(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['homework_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'phase_order', name='uq_phase_output_job_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase_outputs')
    op.drop_index('ix_homework_jobs_status', table_name='homework_jobs')
    op.drop_index('ix_homework_jobs_book_toc', table_name='homework_jobs')
    op.drop_table('homework_jobs')
    op.drop_index('ix_toc_entries_book_id_order', table_name='toc_entries')
    op.drop_table('toc_entries')
    op.drop_index('ix_books_content_sha256', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
