"""add content_type to books

Revision ID: 59a042ea789f
Revises: 22c7641cf558
Create Date: 2026-04-30 19:50:34.930659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a042ea789f'
down_revision: Union[str, Sequence[str], None] = '22c7641cf558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('content_type', sa.String(length=128), server_default='application/pdf', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'content_type')
    # ### end Alembic commands ###
