"""add gemini_usages

Revision ID: f42a38524dfd
Revises: 59a042ea789f
Create Date: 2026-04-30 20:12:26.399981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f42a38524dfd'
down_revision: Union[str, Sequence[str], None] = '59a042ea789f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemini_usages',
    sa.Column('book_id', sa.Uuid(), nullable=True),
    sa.Column('homework_job_id', sa.Uuid(), nullable=True),
    sa.Column('phase_output_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('total_token_count', sa.Integer(), nullable=False),
    sa.Column('input_text_token_count', sa.Integer(), nullable=False),
    sa.Column('input_audio_token_count', sa.Integer(), nullable=False),
    sa.Column('candidates_token_count', sa.Integer(), nullable=False),
    sa.Column('thoughts_token_count', sa.Integer(), nullable=False),
    sa.Column('usage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['homework_job_id'], ['homework_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phase_output_id'], ['phase_outputs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gemini_usages_book', 'gemini_usages', ['book_id'], unique=False)
    op.create_index('ix_gemini_usages_created_at_desc', 'gemini_usages', ['created_at'], unique=False)
    op.create_index('ix_gemini_usages_job', 'gemini_usages', ['homework_job_id'], unique=False)
    op.create_index('ix_gemini_usages_operation', 'gemini_usages', ['operation'], unique=False)
    op.create_index('ix_gemini_usages_phase', 'gemini_usages', ['phase_output_id'], unique=False)
    op.drop_column('books', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('content_type', sa.VARCHAR(length=128), server_default=sa.text("'application/pdf'::character varying"), autoincrement=False, nullable=False))
    op.drop_index('ix_gemini_usages_phase', table_name='gemini_usages')
    op.drop_index('ix_gemini_usages_operation', table_name='gemini_usages')
    op.drop_index('ix_gemini_usages_job', table_name='gemini_usages')
    op.drop_index('ix_gemini_usages_created_at_desc', table_name='gemini_usages')
    op.drop_index('ix_gemini_usages_book', table_name='gemini_usages')
    op.drop_table('gemini_usages')
    # ### end Alembic commands ###
